export const GOOGLE_SERVICES = {
	GA_TRACKING_ID: process.env.NEXT_PUBLIC_GA_TRACKING_ID,
	GA_TAG_MANAGER_ID: process.env.NEXT_PUBLIC_GA_TAG_MANAGER_ID,
	GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
};

export const TG_BOT = {
	TOKEN: process.env.NEXT_PUBLIC_TG_BOT_TOKEN,
	CHAT_ID_LIST: [
		process.env.NEXT_PUBLIC_TG_CHAT_ID_ADMIN,
		process.env.NEXT_PUBLIC_TG_CHAT_ID_NATALIA,
		process.env.NEXT_PUBLIC_TG_CHAT_ID_NATALIA_SECOND,
	],
};
